
spring:
  # 配置数据源类型
  datasource:
#    # 配置连接数据库的各个信息
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/mybatis_plus?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
#    username: root
#    password: root
    dynamic:
      # 设置默认的数据源或者数据源组，默认值即为master
      primary: master
      #严格匹配数据源，默认false。true未匹配到指定数据源是抛异常。false使用默认数据源
      strict: false
      datasource:
        master:
          # 配置连接数据库的各个信息
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/mybatis_plus?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
          username: root
          password: root
        slave:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/mybatis_plus_1?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=false
          username: root
          password: root
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 设置MyBatis-plus的全局配置
  global-config:
    db-config:
      # 设置实体类所对应的表的统一前缀
      table-prefix: t_
      # 设置统一的主键生成策略
      id-type: auto
  # 配置类型别名对应的包
  type-aliases-package: com.zzmhome.mybatisplus.bean
  # 扫描通用枚举的包
  type-enums-package: com.zzmhome.mybatisplus.enums